# Generated by Django 4.0 on 2024-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_book_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='popular',
            field=models.IntegerField(default=0),
        ),
    ]
